/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sidc.vista;

import com.sidc.clases.Persona;
import com.sidc.clases.Sede;
import com.sidc.controllers.ControllerPersona;
import com.sidc.controllers.ControllerSede;
import java.awt.Frame;
import java.awt.Image;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author julian
 */
public class IngresoPersona extends javax.swing.JFrame {

    Persona p;
    static int personaIngresada = 0;

    public static int getPersonaIngresada() {
        return personaIngresada;
    }

    public void setPersonaIngresada(int personaIngresada) {
        this.personaIngresada = personaIngresada;
    }

    /**
     * Creates new form IngresoPersona
     */
    public IngresoPersona() {
        initComponents();
        this.setLocationRelativeTo(null);
         setSize(800,600);
        Persona p = null;
    }
     public Image getIconImage(){
        Image retValue=Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/SIDC (1).png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MuestraDatos = new javax.swing.JFrame();
        btnAtras1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jCalle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlTelefono = new javax.swing.JLabel();
        jlNombre = new javax.swing.JLabel();
        jlApellido = new javax.swing.JLabel();
        jlDni = new javax.swing.JLabel();
        jlFechaNac = new javax.swing.JLabel();
        jEmail = new javax.swing.JLabel();
        jlDireccion = new javax.swing.JLabel();
        verNombre = new javax.swing.JLabel();
        verApellido = new javax.swing.JLabel();
        verDni = new javax.swing.JLabel();
        verFechaNac = new javax.swing.JLabel();
        verTelefono = new javax.swing.JLabel();
        verEmail = new javax.swing.JLabel();
        verCalle = new javax.swing.JLabel();
        verNumero = new javax.swing.JLabel();
        verPiso = new javax.swing.JLabel();
        jlPiso = new javax.swing.JLabel();
        verDpto = new javax.swing.JLabel();
        jlNroHC = new javax.swing.JLabel();
        verNroHC = new javax.swing.JLabel();
        jFrame2 = new javax.swing.JFrame();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnModificar = new javax.swing.JButton();
        btnConsulta = new javax.swing.JButton();
        jlUsuario = new javax.swing.JLabel();
        jlPassword = new javax.swing.JLabel();
        btnAtras = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        txtContraseña = new javax.swing.JPasswordField();
        txtUsuario = new javax.swing.JTextField();
        msjError = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        btnAtras1.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        btnAtras1.setText("Atras");
        btnAtras1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtras1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jCalle.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        jCalle.setText("Calle");
        jCalle.setFocusTraversalPolicyProvider(true);

        jLabel1.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        jLabel1.setText("Numero");

        jLabel3.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        jLabel3.setText("Departamento");

        jlTelefono.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        jlTelefono.setText("Telefono");

        jlNombre.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        jlNombre.setText("Nombre");

        jlApellido.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        jlApellido.setText("Apellido");

        jlDni.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        jlDni.setText("D.N.I.");

        jlFechaNac.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        jlFechaNac.setText("Fecha de nacmiento");

        jEmail.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        jEmail.setText("Email");

        jlDireccion.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        jlDireccion.setText("Direccion");

        jlPiso.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        jlPiso.setText("Piso");

        jlNroHC.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        jlNroHC.setText("Numero Historia Cinica");

        javax.swing.GroupLayout MuestraDatosLayout = new javax.swing.GroupLayout(MuestraDatos.getContentPane());
        MuestraDatos.getContentPane().setLayout(MuestraDatosLayout);
        MuestraDatosLayout.setHorizontalGroup(
            MuestraDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MuestraDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MuestraDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MuestraDatosLayout.createSequentialGroup()
                        .addGap(0, 50, Short.MAX_VALUE)
                        .addComponent(jlDireccion)
                        .addGap(110, 110, 110)
                        .addComponent(btnAtras1)
                        .addGap(33, 33, 33)
                        .addComponent(jButton2))
                    .addGroup(MuestraDatosLayout.createSequentialGroup()
                        .addGroup(MuestraDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MuestraDatosLayout.createSequentialGroup()
                                .addGroup(MuestraDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlApellido)
                                    .addComponent(jlDni)
                                    .addComponent(jlFechaNac)
                                    .addComponent(jlTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(96, 96, 96)
                                .addGroup(MuestraDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(verCalle)
                                    .addComponent(verEmail)
                                    .addComponent(verTelefono)
                                    .addComponent(verFechaNac)
                                    .addComponent(verDni)
                                    .addComponent(verApellido)
                                    .addComponent(verNombre)))
                            .addGroup(MuestraDatosLayout.createSequentialGroup()
                                .addGroup(MuestraDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jlPiso)
                                    .addGroup(MuestraDatosLayout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(172, 172, 172)
                                        .addComponent(verNumero)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(MuestraDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(verPiso)
                                    .addComponent(verDpto)
                                    .addComponent(verNroHC)))
                            .addComponent(jlNroHC))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        MuestraDatosLayout.setVerticalGroup(
            MuestraDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MuestraDatosLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(MuestraDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNroHC)
                    .addComponent(verNroHC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MuestraDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNombre)
                    .addComponent(verNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MuestraDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlApellido)
                    .addComponent(verApellido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MuestraDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDni)
                    .addComponent(verDni))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MuestraDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlFechaNac)
                    .addComponent(verFechaNac))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MuestraDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTelefono)
                    .addComponent(verTelefono))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MuestraDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEmail)
                    .addComponent(verEmail))
                .addGap(8, 8, 8)
                .addComponent(jlDireccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MuestraDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(verCalle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MuestraDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(verNumero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MuestraDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(verPiso)
                    .addComponent(jlPiso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MuestraDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(verDpto)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(MuestraDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAtras1)
                    .addComponent(jButton2))
                .addGap(188, 188, 188))
        );

        jFrame2.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 624, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 271, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("antecedente", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 624, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 271, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("sedes", jPanel3);

        btnModificar.setText("modificar datos");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnConsulta.setActionCommand("consultar datos");
        btnConsulta.setLabel("consultar datos");
        btnConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnConsulta)
                .addGap(28, 28, 28)
                .addComponent(btnModificar)
                .addGap(0, 374, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsulta)
                    .addComponent(btnModificar))
                .addGap(0, 237, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("datos personales", jPanel1);

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(174, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlUsuario.setFont(new java.awt.Font("Gill Sans MT", 3, 18)); // NOI18N
        jlUsuario.setForeground(new java.awt.Color(0, 153, 153));
        jlUsuario.setText("D.N.I.");
        getContentPane().add(jlUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 107, -1));

        jlPassword.setFont(new java.awt.Font("Gill Sans MT", 3, 18)); // NOI18N
        jlPassword.setForeground(new java.awt.Color(0, 153, 153));
        jlPassword.setText("Contraseña");
        getContentPane().add(jlPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 107, -1));

        btnAtras.setBackground(new java.awt.Color(0, 0, 0));
        btnAtras.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        btnAtras.setForeground(new java.awt.Color(0, 153, 153));
        btnAtras.setText("Atras");
        btnAtras.setBorderPainted(false);
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, -1, -1));

        btnSiguiente.setBackground(new java.awt.Color(0, 0, 0));
        btnSiguiente.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        btnSiguiente.setForeground(new java.awt.Color(0, 153, 153));
        btnSiguiente.setText("Siguiente");
        btnSiguiente.setBorderPainted(false);
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 550, -1, -1));

        btnSalir.setBackground(new java.awt.Color(0, 0, 0));
        btnSalir.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(0, 153, 153));
        btnSalir.setText("Salir");
        btnSalir.setBorderPainted(false);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, -1, -1));

        txtContraseña.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        txtContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraseñaActionPerformed(evt);
            }
        });
        getContentPane().add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 210, 30));

        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 210, 30));

        msjError.setFont(new java.awt.Font("Gill Sans MT", 3, 18)); // NOI18N
        msjError.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(msjError, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dnarelo.gif"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        personaIngresada = Integer.parseInt(txtUsuario.getText());
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        TestMainAUsar t = new TestMainAUsar();
        t.setVisible(true);
        t.setLocationRelativeTo(null);
        //t.dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        SeleccionIngreso t = new SeleccionIngreso();
        t.setVisible(true);
        t.setLocationRelativeTo(null);
        //t.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
      
            msjError.setText("Usuario y/o contraseña invalidos.");
        
        personaIngresada = Integer.parseInt(txtUsuario.getText());
        p = ControllerPersona.getPersonaByDni(personaIngresada);
        //if (ControllerPersona.habilitar(p, p.getPassword())) {
        //Ventana3 dp = new VentanaPersona();
        //dp.setVisible(true);
        //dp.setLocationRelativeTo(null);

        VentanaPersona vp = new VentanaPersona();
        vp.setVisible(true);
        vp.txtNombre.setText(p.getNombre());
        vp.setTxtApellido(p.getApellido());
        vp.setTxtNrohc(String.valueOf(p.getNroHistoriaClinica()));
        vp.setTxtDni(String.valueOf(p.getDni()));
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        String fechaComoCadena = sdf.format(p.getFechaNacimiento());
        vp.setTxtFechaNacimiento(fechaComoCadena);
        vp.setTxtTelefono(p.getTelefono());
        vp.setTxtEmail(p.getEmail());
        vp.setTxtCalle(p.getCalle());
        vp.setTxtNumero(String.valueOf(p.getNumero()));
        vp.setTxtPiso(String.valueOf(p.getPiso()));
        vp.setTxtDpto(p.getLetra());
        //MuestraDatos.setLocationRelativeTo(null);


    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnAtras1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtras1ActionPerformed
        VentanaPersona t = new VentanaPersona();
        t.setVisible(true);
        t.setLocationRelativeTo(null); // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnAtras1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        TestMainAUsar t = new TestMainAUsar();
        t.setVisible(true);
        t.setLocationRelativeTo(null); // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        int numEntero = Integer.parseInt(txtUsuario.getText());
        p = ControllerPersona.getPersonaByDni(numEntero);
        RegistrarPersona d1 = new RegistrarPersona();
        d1.setVisible(true);// TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaActionPerformed

        int numEntero = Integer.parseInt("30911509");//txtUsuario.getText());
        p = ControllerPersona.getPersonaByDni(numEntero);
        verNombre.setText(p.getNombre());
        verApellido.setText(p.getApellido());
        verDni.setText(txtUsuario.getText());
        //verFechaNac.setText(string);
        MuestraDatos.setVisible(true);
        //VerDatos d1=new VerDatos();

        // d1.setVisible(true); // TODO add your handling code here:
        MuestraDatos.setLocationRelativeTo(null);
        //this.dispose();
        

    }//GEN-LAST:event_btnConsultaActionPerformed

    private void txtContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraseñaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresoPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresoPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresoPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresoPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresoPersona().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame MuestraDatos;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnAtras1;
    private javax.swing.JButton btnConsulta;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jCalle;
    private javax.swing.JLabel jEmail;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel jlApellido;
    private javax.swing.JLabel jlDireccion;
    private javax.swing.JLabel jlDni;
    private javax.swing.JLabel jlFechaNac;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JLabel jlNroHC;
    private javax.swing.JLabel jlPassword;
    private javax.swing.JLabel jlPiso;
    private javax.swing.JLabel jlTelefono;
    private javax.swing.JLabel jlUsuario;
    private javax.swing.JLabel msjError;
    private javax.swing.JPasswordField txtContraseña;
    public static javax.swing.JTextField txtUsuario;
    private javax.swing.JLabel verApellido;
    private javax.swing.JLabel verCalle;
    private javax.swing.JLabel verDni;
    private javax.swing.JLabel verDpto;
    private javax.swing.JLabel verEmail;
    private javax.swing.JLabel verFechaNac;
    private javax.swing.JLabel verNombre;
    private javax.swing.JLabel verNroHC;
    private javax.swing.JLabel verNumero;
    private javax.swing.JLabel verPiso;
    private javax.swing.JLabel verTelefono;
    // End of variables declaration//GEN-END:variables

    public JTextField getTxtUsuario() {
        return txtUsuario;
    }

    public void setTxtNombre(JTextField txtUsuario) {
        this.txtUsuario = txtUsuario;
    }

}
