/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sidc.vista;

import com.sidc.clases.Persona;
import static com.sidc.controllers.ControllerPersona.insertarPersona;
import static com.sidc.main.img.MainSwing.isLogueado;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author julian
 */
public class RegistrarPersona extends javax.swing.JFrame {

    private Persona p1;

    /**
     * Creates new form datosPersonales
     */
    public RegistrarPersona() {
        initComponents();
        this.setLocationRelativeTo(null);

    }
     public Image getIconImage(){
        Image retValue=Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/SIDC (1).png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlNroHC = new javax.swing.JLabel();
        jCalle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlTelefono = new javax.swing.JLabel();
        jlNombre = new javax.swing.JLabel();
        jlApellido = new javax.swing.JLabel();
        jlFechaNac = new javax.swing.JLabel();
        jEmail = new javax.swing.JLabel();
        jlDireccion = new javax.swing.JLabel();
        btnAtras4 = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        txtNroHC = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtDia = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtCalle = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        txtPiso = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDpto = new javax.swing.JTextField();
        jlDni = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblResultado = new javax.swing.JLabel();
        btnRegistar = new javax.swing.JButton();
        jlContraseña = new javax.swing.JLabel();
        txtContraseña = new javax.swing.JPasswordField();
        txtMes = new javax.swing.JTextField();
        txtAño = new javax.swing.JTextField();
        jlFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setFocusable(false);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlNroHC.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        jlNroHC.setForeground(new java.awt.Color(0, 153, 153));
        jlNroHC.setText("Numero Historia Clinica");
        getContentPane().add(jlNroHC, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 209, -1, -1));

        jCalle.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        jCalle.setForeground(new java.awt.Color(0, 153, 153));
        jCalle.setText("Calle");
        jCalle.setFocusTraversalPolicyProvider(true);
        getContentPane().add(jCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 346, 103, 12));

        jLabel1.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Numero");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        jLabel3.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 153));
        jLabel3.setText("Departamento");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 427, -1, -1));

        jlTelefono.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        jlTelefono.setForeground(new java.awt.Color(0, 153, 153));
        jlTelefono.setText("Telefono");
        getContentPane().add(jlTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 157, 127, -1));

        jlNombre.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        jlNombre.setForeground(new java.awt.Color(0, 153, 153));
        jlNombre.setText("Nombre");
        getContentPane().add(jlNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 53, 63, -1));

        jlApellido.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        jlApellido.setForeground(new java.awt.Color(0, 153, 153));
        jlApellido.setText("Apellido");
        getContentPane().add(jlApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 79, -1, -1));

        jlFechaNac.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        jlFechaNac.setForeground(new java.awt.Color(0, 153, 153));
        jlFechaNac.setText("Fecha de nacimiento(dd/mm/yyyy)");
        getContentPane().add(jlFechaNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 131, -1, -1));

        jEmail.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        jEmail.setForeground(new java.awt.Color(0, 153, 153));
        jEmail.setText("Email");
        getContentPane().add(jEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 183, 78, -1));

        jlDireccion.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        jlDireccion.setForeground(new java.awt.Color(0, 153, 153));
        jlDireccion.setText("Direccion");
        getContentPane().add(jlDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 320, -1, -1));

        btnAtras4.setBackground(new java.awt.Color(0, 0, 0));
        btnAtras4.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        btnAtras4.setForeground(new java.awt.Color(0, 153, 153));
        btnAtras4.setText("Atras");
        btnAtras4.setBorderPainted(false);
        btnAtras4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtras4ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtras4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, -1, -1));

        btnSalir.setBackground(btnAtras4.getBackground());
        btnSalir.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(0, 153, 153));
        btnSalir.setText("Salir");
        btnSalir.setBorderPainted(false);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, -1, -1));
        getContentPane().add(txtNroHC, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 208, 149, -1));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 52, 149, -1));
        getContentPane().add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 78, 149, -1));

        txtDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiaActionPerformed(evt);
            }
        });
        getContentPane().add(txtDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 30, -1));
        getContentPane().add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 156, 149, -1));
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 182, 149, -1));
        getContentPane().add(txtCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 343, 149, -1));

        txtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroActionPerformed(evt);
            }
        });
        getContentPane().add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 369, 149, -1));

        txtPiso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPisoActionPerformed(evt);
            }
        });
        getContentPane().add(txtPiso, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 395, 149, -1));

        jLabel4.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setText("Piso");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 396, -1, -1));
        getContentPane().add(txtDpto, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 426, 149, -1));

        jlDni.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        jlDni.setForeground(new java.awt.Color(0, 153, 153));
        jlDni.setText("DNI");
        getContentPane().add(jlDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 105, -1, -1));
        getContentPane().add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 104, 149, -1));

        jLabel2.setFont(new java.awt.Font("Gill Sans MT", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("Registro de Persona");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 19, -1, -1));

        lblResultado.setFont(new java.awt.Font("Gill Sans MT", 3, 18)); // NOI18N
        lblResultado.setForeground(new java.awt.Color(51, 153, 0));
        getContentPane().add(lblResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 452, 560, 50));

        btnRegistar.setBackground(btnAtras4.getBackground());
        btnRegistar.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        btnRegistar.setForeground(new java.awt.Color(0, 153, 153));
        btnRegistar.setText("Registrar");
        btnRegistar.setBorderPainted(false);
        btnRegistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 510, -1, -1));

        jlContraseña.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        jlContraseña.setForeground(new java.awt.Color(0, 153, 153));
        jlContraseña.setText("Contraseña");
        getContentPane().add(jlContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 235, -1, -1));

        txtContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraseñaActionPerformed(evt);
            }
        });
        getContentPane().add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 234, 149, -1));
        getContentPane().add(txtMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 130, 35, -1));

        txtAño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAñoActionPerformed(evt);
            }
        });
        getContentPane().add(txtAño, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 130, 72, -1));

        jlFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dna-background-9242.jpeg"))); // NOI18N
        getContentPane().add(jlFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-510, 0, 1290, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtras4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtras4ActionPerformed
        SeleccionIngreso t = new SeleccionIngreso();
        t.setVisible(true);
        t.setLocationRelativeTo(null); // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnAtras4ActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        TestMainAUsar t = new TestMainAUsar();
        t.setVisible(true);
        t.setLocationRelativeTo(null); // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroActionPerformed

    private void txtPisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPisoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPisoActionPerformed

    private void btnRegistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistarActionPerformed

        int dni = 0;
        try {
            int ndni = Integer.parseInt(txtDni.getText());
            dni = ndni;
        } catch (NumberFormatException nfe) {
            System.err.println("Error de conversion de " + txtDni.getText() + ": " + nfe.getMessage());
            lblResultado.setForeground(Color.red); 
            lblResultado.setText("No se ha regitrado,verifique los datos");
            //agregar ventana de aviso del error
        }

        String nombre = txtNombre.getText();
        String apellido = txtApellido.getText();
        String s = null;
        int nroHC = 0;
        try {
            s = txtNroHC.getText();
            nroHC = Integer.parseInt(s);
        } catch (NumberFormatException nfe) {
            System.err.println("Error de conversion de " + s + ": " + nfe.getMessage());
            lblResultado.setForeground(Color.red);
            lblResultado.setText("No se ha regitrado,verifique los datos");
        }

        //Date fechaNacimiento = ParseFecha(txtFechaNac.getText());
        //SimpleDateFormat sdf = new SimpleDateFormat();
        //String fechaComoCadena = sdf.format(new Date(txtDia.getText() + "," + txtMes.getText() + "," + txtAño.getText()));
        //Date fechaNacimiento = ParseFecha(fechaComoCadena);
        Date fechaNacimiento = new Date (Integer.parseInt(txtAño.getText())-1900,Integer.parseInt(txtMes.getText())-1,Integer.parseInt(txtDia.getText())-1);
        String telefono = txtTelefono.getText();
        String email = txtEmail.getText();
        String contraseña = txtContraseña.getText();
        String calle = txtCalle.getText();
        int numero = 0;
        try {
            int numeroAux = Integer.parseInt(txtNumero.getText().trim());
            numero = numeroAux;
        } catch (NumberFormatException nfe) {
            System.err.println("Error de conversion de " + s + ": " + nfe.getMessage());
            lblResultado.setForeground(Color.red);
            lblResultado.setText("No se ha regitrado,verifique los datos");
        }

        int piso = Integer.parseInt(txtPiso.getText().trim());
        String dpto = txtDpto.getText();
        Persona p1 = new Persona(dni, nombre, apellido, fechaNacimiento, email, telefono, nroHC, contraseña, calle, numero, piso, dpto);
        insertarPersona(p1);
        if (isLogueado()) {
            lblResultado.setForeground(Color.red);
            lblResultado.setText("No se ha regitrado,verifique los datos");
        } else {
            lblResultado.setText("Persona regitrada correctamente");
        }
    }//GEN-LAST:event_btnRegistarActionPerformed

    private void txtContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraseñaActionPerformed

    private void txtDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiaActionPerformed

    private void txtAñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAñoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAñoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarPersona().setVisible(true);
            }
        });
    }

    public Date ParseFecha(String fecha) {
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        Date fechaDate = null;
        try {
            fechaDate = formato.parse(fecha);
        } catch (ParseException ex) {
            System.out.println(ex);
        }
        return fechaDate;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras4;
    private javax.swing.JButton btnRegistar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jCalle;
    private javax.swing.JLabel jEmail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jlApellido;
    private javax.swing.JLabel jlContraseña;
    private javax.swing.JLabel jlDireccion;
    private javax.swing.JLabel jlDni;
    private javax.swing.JLabel jlFechaNac;
    private javax.swing.JLabel jlFondo;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JLabel jlNroHC;
    private javax.swing.JLabel jlTelefono;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtAño;
    private javax.swing.JTextField txtCalle;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtDia;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtDpto;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtMes;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNroHC;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtPiso;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
