/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sidc.vista;

import com.sidc.clases.Persona;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author julian
 */
public class SeleccionIngreso extends javax.swing.JFrame {
     private Persona persona;
    /**
     * Creates new form Ventana2
     */
    public SeleccionIngreso() {
        initComponents();
        setSize(800,600);
        seleccionUsuario.add(jrbUsuario);
        seleccionUsuario.add(jrbMedico);
        seleccionUsuario.add(jrbSede);
        
    }
     public Image getIconImage(){
       Image retValue=Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/SIDC (1).png"));
        return retValue;
  }

    public String seleccionAdministrador(){
        if(jrbUsuario.isSelected()){
            return jrbUsuario.getText();
        }
        if(jrbMedico.isSelected()){
        return jrbMedico.getText();
        }
        if(jrbSede.isSelected()){
            return jrbSede.getText();
        }
        return JOptionPane.INPUT_VALUE_PROPERTY;
        }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seleccionUsuario = new javax.swing.ButtonGroup();
        jrbUsuario = new javax.swing.JRadioButton();
        jrbMedico = new javax.swing.JRadioButton();
        jrbSede = new javax.swing.JRadioButton();
        txtCabecera_v2 = new javax.swing.JLabel();
        jbIgresar = new javax.swing.JButton();
        btnRegistar = new javax.swing.JButton();
        msjError = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ingresar datos");
        setIconImage(getIconImage());
        setIconImages(getIconImages());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jrbUsuario.setFont(new java.awt.Font("Gill Sans MT", 3, 12)); // NOI18N
        jrbUsuario.setForeground(new java.awt.Color(0, 153, 153));
        jrbUsuario.setToolTipText("");
        jrbUsuario.setActionCommand("rbtnUsuario");
        jrbUsuario.setLabel("Usuario");
        jrbUsuario.setOpaque(false);
        jrbUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jrbUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, -1, -1));

        jrbMedico.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        jrbMedico.setForeground(new java.awt.Color(0, 153, 153));
        jrbMedico.setText("Medico");
        jrbMedico.setOpaque(false);
        jrbMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbMedicoActionPerformed(evt);
            }
        });
        getContentPane().add(jrbMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, -1, -1));

        jrbSede.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        jrbSede.setForeground(new java.awt.Color(0, 153, 153));
        jrbSede.setText("Sede");
        jrbSede.setOpaque(false);
        jrbSede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbSedeActionPerformed(evt);
            }
        });
        getContentPane().add(jrbSede, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, -1, -1));

        txtCabecera_v2.setFont(new java.awt.Font("Gill Sans MT", 3, 18)); // NOI18N
        txtCabecera_v2.setForeground(new java.awt.Color(0, 153, 153));
        txtCabecera_v2.setText("Seleccione tipo de usuario");
        getContentPane().add(txtCabecera_v2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 215, 25));
        txtCabecera_v2.getAccessibleContext().setAccessibleName("txtCabecera_v2");

        jbIgresar.setBackground(new java.awt.Color(0, 0, 0));
        jbIgresar.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        jbIgresar.setForeground(new java.awt.Color(0, 153, 153));
        jbIgresar.setText("Ingresar");
        jbIgresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbIgresarActionPerformed(evt);
            }
        });
        getContentPane().add(jbIgresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, 110, -1));

        btnRegistar.setBackground(new java.awt.Color(0, 0, 0));
        btnRegistar.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        btnRegistar.setForeground(new java.awt.Color(0, 153, 153));
        btnRegistar.setText("Registrarse");
        btnRegistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 490, 110, -1));

        msjError.setFont(new java.awt.Font("Gill Sans MT", 3, 18)); // NOI18N
        msjError.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(msjError, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, -1));

        btnSalir.setBackground(new java.awt.Color(0, 0, 0));
        btnSalir.setFont(new java.awt.Font("Gill Sans MT", 3, 18)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(0, 153, 153));
        btnSalir.setText("Salir");
        btnSalir.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, 70, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/theone.gif"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrbSedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbSedeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbSedeActionPerformed

    private void jrbMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbMedicoActionPerformed

    private void jbIgresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbIgresarActionPerformed
       if(jrbUsuario.isSelected()){
           IngresoPersona ip=new IngresoPersona();
           ip.setVisible(true);// TODO add your handling code here:
           ip.setLocationRelativeTo(null);
           this.dispose();
       }
       if(jrbMedico.isSelected()){
           IngresoMedico im=new IngresoMedico();
           im.setVisible(true);// TODO add your handling code here:
           im.setLocationRelativeTo(null);
           this.dispose();
       }
         if(jrbSede.isSelected()){
           IngresoSede is=new IngresoSede();
           is.setVisible(true);// TODO add your handling code here:
           is.setLocationRelativeTo(null);
           this.dispose();
    }//GEN-LAST:event_jbIgresarActionPerformed
    if(!(jrbUsuario.isSelected())&&!(jrbMedico.isSelected())&&!(jrbSede.isSelected())){
        msjError.setText("Seleccione un tipo de usuario para ingresar");
    }
    }
    private void jrbUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbUsuarioActionPerformed
       
// TODO add your handling code here:
    }//GEN-LAST:event_jrbUsuarioActionPerformed

    private void btnRegistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistarActionPerformed
        RegistrarPersona reg= new RegistrarPersona();
        reg.setVisible(true);
        reg.setLocationRelativeTo(null);// TODO add your handling code here:
    }//GEN-LAST:event_btnRegistarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeleccionIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeleccionIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeleccionIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeleccionIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeleccionIngreso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jbIgresar;
    private javax.swing.JRadioButton jrbMedico;
    private javax.swing.JRadioButton jrbSede;
    private javax.swing.JRadioButton jrbUsuario;
    private javax.swing.JLabel msjError;
    private javax.swing.ButtonGroup seleccionUsuario;
    private javax.swing.JLabel txtCabecera_v2;
    // End of variables declaration//GEN-END:variables
}
