/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sidc.vista;

import com.sidc.clases.Alergia;
import com.sidc.clases.HistoriaClinica;
import com.sidc.clases.Persona;
import com.sidc.clases.Sede;
import com.sidc.clases.Vacuna;
import com.sidc.controllers.ControllerHistoriaClinica;
import com.sidc.controllers.ControllerPersona;
import static com.sidc.controllers.ControllerPersona.getPersonaByDni;
import com.sidc.controllers.ControllerSede;
import com.sidc.main.img.MainSwing;
import java.awt.Image;
import java.awt.TextField;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author julian
 */
public class VentanaPersona extends javax.swing.JFrame {
 DefaultTableModel modelo;
 DefaultTableModel modeloV;
 DefaultTableModel modeloA;
    /**
     * Creates new form Ventana3
     */
    public VentanaPersona() {
        initComponents();
        this.setLocationRelativeTo(null);
        setSize(800,600);
        CrearModeloSede();
        CrearModeloAlergia();
        CrearModeloVacuna();
          
    }
    
    
    
    
  
     public Image getIconImage(){
        Image retValue=Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/SIDC (1).png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MuestraDatos = new javax.swing.JFrame();
        btnAtras = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jCalle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlTelefono = new javax.swing.JLabel();
        jlNombre = new javax.swing.JLabel();
        jlApellido = new javax.swing.JLabel();
        jlDni = new javax.swing.JLabel();
        jlFechaNac = new javax.swing.JLabel();
        jEmail = new javax.swing.JLabel();
        jlDireccion = new javax.swing.JLabel();
        verNombre = new javax.swing.JLabel();
        verApellido = new javax.swing.JLabel();
        verDni = new javax.swing.JLabel();
        verFechaNac = new javax.swing.JLabel();
        verTelefono = new javax.swing.JLabel();
        verEmail = new javax.swing.JLabel();
        verCalle = new javax.swing.JLabel();
        verNumero = new javax.swing.JLabel();
        verPiso = new javax.swing.JLabel();
        jlPiso = new javax.swing.JLabel();
        verDpto = new javax.swing.JLabel();
        jlNroHC = new javax.swing.JLabel();
        verNroHC = new javax.swing.JLabel();
        jTabbeDatos = new javax.swing.JTabbedPane();
        historiaClinica = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnMostrarHC = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        alergias = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableAlergias = new javax.swing.JTable();
        btnMostrarAlergias = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        vacunas = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableVacuna = new javax.swing.JTable();
        btnMostrarVacunas = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        sedes = new javax.swing.JPanel();
        jScrollPaneSedes = new javax.swing.JScrollPane();
        tablaSedes = new javax.swing.JTable();
        btnMostrarSedes = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        datosPersonales = new javax.swing.JPanel();
        jlNroHC1 = new javax.swing.JLabel();
        jCalle1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jlTelefono1 = new javax.swing.JLabel();
        jlApellido1 = new javax.swing.JLabel();
        jlDni1 = new javax.swing.JLabel();
        jlFechaNac1 = new javax.swing.JLabel();
        jEmail1 = new javax.swing.JLabel();
        jlPiso1 = new javax.swing.JLabel();
        txtNrohc = new java.awt.TextField();
        txtNombre = new java.awt.TextField();
        txtApellido = new java.awt.TextField();
        txtDni = new java.awt.TextField();
        txtFechaNacimiento = new java.awt.TextField();
        txtTelefono = new java.awt.TextField();
        txtEmail = new java.awt.TextField();
        txtCalle = new java.awt.TextField();
        txtNumero = new java.awt.TextField();
        txtPiso = new java.awt.TextField();
        txtDpto = new java.awt.TextField();
        btnModificar = new javax.swing.JButton();
        lbNombre = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        MuestraDatos.setSize(new java.awt.Dimension(600, 400));

        btnAtras.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jCalle.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        jCalle.setText("Calle");
        jCalle.setFocusTraversalPolicyProvider(true);

        jLabel1.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        jLabel1.setText("Numero");

        jLabel3.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        jLabel3.setText("Departamento");

        jlTelefono.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        jlTelefono.setText("Telefono");

        jlNombre.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        jlNombre.setText("Nombre");

        jlApellido.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        jlApellido.setText("Apellido");

        jlDni.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        jlDni.setText("D.N.I.");

        jlFechaNac.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        jlFechaNac.setText("Fecha de nacmiento");

        jEmail.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        jEmail.setText("Email");

        jlDireccion.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        jlDireccion.setText("Direccion");

        jlPiso.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        jlPiso.setText("Piso");

        jlNroHC.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        jlNroHC.setText("Numero Historia Cinica");

        javax.swing.GroupLayout MuestraDatosLayout = new javax.swing.GroupLayout(MuestraDatos.getContentPane());
        MuestraDatos.getContentPane().setLayout(MuestraDatosLayout);
        MuestraDatosLayout.setHorizontalGroup(
            MuestraDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MuestraDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MuestraDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MuestraDatosLayout.createSequentialGroup()
                        .addGap(0, 304, Short.MAX_VALUE)
                        .addGroup(MuestraDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MuestraDatosLayout.createSequentialGroup()
                                .addComponent(jlDireccion)
                                .addGap(279, 279, 279))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MuestraDatosLayout.createSequentialGroup()
                                .addComponent(btnAtras)
                                .addGap(32, 32, 32)
                                .addComponent(jButton2)
                                .addGap(49, 49, 49))))
                    .addGroup(MuestraDatosLayout.createSequentialGroup()
                        .addGroup(MuestraDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MuestraDatosLayout.createSequentialGroup()
                                .addGroup(MuestraDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlApellido)
                                    .addComponent(jlDni)
                                    .addComponent(jlFechaNac)
                                    .addComponent(jlTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(96, 96, 96)
                                .addGroup(MuestraDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(verCalle)
                                    .addComponent(verEmail)
                                    .addComponent(verTelefono)
                                    .addComponent(verFechaNac)
                                    .addComponent(verDni)
                                    .addComponent(verApellido)
                                    .addComponent(verNombre)))
                            .addGroup(MuestraDatosLayout.createSequentialGroup()
                                .addGroup(MuestraDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jlPiso)
                                    .addGroup(MuestraDatosLayout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(172, 172, 172)
                                        .addComponent(verNumero)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(MuestraDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(verPiso)
                                    .addComponent(verDpto)
                                    .addComponent(verNroHC)))
                            .addComponent(jlNroHC))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        MuestraDatosLayout.setVerticalGroup(
            MuestraDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MuestraDatosLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(MuestraDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNroHC)
                    .addComponent(verNroHC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MuestraDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNombre)
                    .addComponent(verNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MuestraDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlApellido)
                    .addComponent(verApellido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MuestraDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDni)
                    .addComponent(verDni))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MuestraDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlFechaNac)
                    .addComponent(verFechaNac))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MuestraDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTelefono)
                    .addComponent(verTelefono))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MuestraDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEmail)
                    .addComponent(verEmail))
                .addGap(8, 8, 8)
                .addComponent(jlDireccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MuestraDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(verCalle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MuestraDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(verNumero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MuestraDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(verPiso)
                    .addComponent(jlPiso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MuestraDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(verDpto)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addGroup(MuestraDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAtras)
                    .addComponent(jButton2))
                .addGap(188, 188, 188))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbeDatos.setBackground(new java.awt.Color(0, 0, 0));
        jTabbeDatos.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTabbeDatos.setForeground(new java.awt.Color(0, 153, 153));
        jTabbeDatos.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Fecha", "Especialidad", "Diagnóstico", "Matrícula Médico"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnMostrarHC.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        btnMostrarHC.setForeground(new java.awt.Color(0, 153, 153));
        btnMostrarHC.setText("Mostrar Antecedentes");

        jButton5.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 153, 153));
        jButton5.setText("Salir");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout historiaClinicaLayout = new javax.swing.GroupLayout(historiaClinica);
        historiaClinica.setLayout(historiaClinicaLayout);
        historiaClinicaLayout.setHorizontalGroup(
            historiaClinicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(historiaClinicaLayout.createSequentialGroup()
                .addGroup(historiaClinicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMostrarHC)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE))
        );
        historiaClinicaLayout.setVerticalGroup(
            historiaClinicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
            .addGroup(historiaClinicaLayout.createSequentialGroup()
                .addComponent(btnMostrarHC)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbeDatos.addTab("Historia Clinica", historiaClinica);

        jTableAlergias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTableAlergias);

        btnMostrarAlergias.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        btnMostrarAlergias.setForeground(new java.awt.Color(0, 153, 153));
        btnMostrarAlergias.setText("Mostrar Alergias");
        btnMostrarAlergias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarAlergiasActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 153, 153));
        jButton3.setText("Salir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout alergiasLayout = new javax.swing.GroupLayout(alergias);
        alergias.setLayout(alergiasLayout);
        alergiasLayout.setHorizontalGroup(
            alergiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alergiasLayout.createSequentialGroup()
                .addGroup(alergiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMostrarAlergias)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE))
        );
        alergiasLayout.setVerticalGroup(
            alergiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
            .addGroup(alergiasLayout.createSequentialGroup()
                .addComponent(btnMostrarAlergias)
                .addGap(29, 29, 29)
                .addComponent(jButton3)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbeDatos.addTab("Alergias", alergias);

        jTableVacuna.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jTableVacuna);

        btnMostrarVacunas.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        btnMostrarVacunas.setForeground(new java.awt.Color(0, 153, 153));
        btnMostrarVacunas.setText("Mostrar Vacunas");
        btnMostrarVacunas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarVacunasActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 153, 153));
        jButton4.setText("Salir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout vacunasLayout = new javax.swing.GroupLayout(vacunas);
        vacunas.setLayout(vacunasLayout);
        vacunasLayout.setHorizontalGroup(
            vacunasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vacunasLayout.createSequentialGroup()
                .addGroup(vacunasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMostrarVacunas)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE))
        );
        vacunasLayout.setVerticalGroup(
            vacunasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
            .addGroup(vacunasLayout.createSequentialGroup()
                .addComponent(btnMostrarVacunas)
                .addGap(33, 33, 33)
                .addComponent(jButton4)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbeDatos.addTab("Vacunas", vacunas);

        tablaSedes.setForeground(new java.awt.Color(0, 153, 153));
        tablaSedes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaSedes.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                tablaSedesComponentAdded(evt);
            }
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                tablaSedesComponentRemoved(evt);
            }
        });
        jScrollPaneSedes.setViewportView(tablaSedes);
        tablaSedes.getAccessibleContext().setAccessibleName("");

        btnMostrarSedes.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        btnMostrarSedes.setForeground(new java.awt.Color(0, 153, 153));
        btnMostrarSedes.setText("Mostrar");
        btnMostrarSedes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarSedesActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 153, 153));
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sedesLayout = new javax.swing.GroupLayout(sedes);
        sedes.setLayout(sedesLayout);
        sedesLayout.setHorizontalGroup(
            sedesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sedesLayout.createSequentialGroup()
                .addGroup(sedesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sedesLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMostrarSedes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(sedesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPaneSedes, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        sedesLayout.setVerticalGroup(
            sedesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneSedes, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
            .addGroup(sedesLayout.createSequentialGroup()
                .addComponent(btnMostrarSedes)
                .addGap(52, 52, 52)
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbeDatos.addTab("Sedes", sedes);

        datosPersonales.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlNroHC1.setFont(new java.awt.Font("Gill Sans MT", 3, 18)); // NOI18N
        jlNroHC1.setForeground(new java.awt.Color(0, 153, 153));
        jlNroHC1.setText("Numero Historia Cinica");
        datosPersonales.add(jlNroHC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 83, -1, -1));

        jCalle1.setFont(new java.awt.Font("Gill Sans MT", 3, 18)); // NOI18N
        jCalle1.setForeground(new java.awt.Color(0, 153, 153));
        jCalle1.setText("Calle");
        jCalle1.setFocusTraversalPolicyProvider(true);
        datosPersonales.add(jCalle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 103, 20));

        jLabel2.setFont(new java.awt.Font("Gill Sans MT", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("Numero");
        datosPersonales.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, -1, -1));

        jLabel4.setFont(new java.awt.Font("Gill Sans MT", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setText("Departamento");
        datosPersonales.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, -1, -1));

        jlTelefono1.setFont(new java.awt.Font("Gill Sans MT", 3, 18)); // NOI18N
        jlTelefono1.setForeground(new java.awt.Color(0, 153, 153));
        jlTelefono1.setText("Telefono");
        datosPersonales.add(jlTelefono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 247, 127, -1));

        jlApellido1.setFont(new java.awt.Font("Gill Sans MT", 3, 18)); // NOI18N
        jlApellido1.setForeground(new java.awt.Color(0, 153, 153));
        jlApellido1.setText("Apellido");
        datosPersonales.add(jlApellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 151, -1, -1));

        jlDni1.setFont(new java.awt.Font("Gill Sans MT", 3, 18)); // NOI18N
        jlDni1.setForeground(new java.awt.Color(0, 153, 153));
        jlDni1.setText("D.N.I.");
        datosPersonales.add(jlDni1, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 183, -1, -1));

        jlFechaNac1.setFont(new java.awt.Font("Gill Sans MT", 3, 18)); // NOI18N
        jlFechaNac1.setForeground(new java.awt.Color(0, 153, 153));
        jlFechaNac1.setText("Fecha de nacmiento");
        datosPersonales.add(jlFechaNac1, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 215, -1, -1));

        jEmail1.setFont(new java.awt.Font("Gill Sans MT", 3, 18)); // NOI18N
        jEmail1.setForeground(new java.awt.Color(0, 153, 153));
        jEmail1.setText("Email");
        datosPersonales.add(jEmail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 280, 78, -1));

        jlPiso1.setFont(new java.awt.Font("Gill Sans MT", 3, 18)); // NOI18N
        jlPiso1.setForeground(new java.awt.Color(0, 153, 153));
        jlPiso1.setText("Piso");
        datosPersonales.add(jlPiso1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, -1, -1));

        txtNrohc.setEnabled(false);
        txtNrohc.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        txtNrohc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNrohcActionPerformed(evt);
            }
        });
        datosPersonales.add(txtNrohc, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 85, 122, 20));

        txtNombre.setEnabled(false);
        txtNombre.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        datosPersonales.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 120, 122, -1));

        txtApellido.setEnabled(false);
        txtApellido.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        datosPersonales.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 152, 122, -1));

        txtDni.setEnabled(false);
        txtDni.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        txtDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDniActionPerformed(evt);
            }
        });
        datosPersonales.add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 184, 122, -1));

        txtFechaNacimiento.setEnabled(false);
        txtFechaNacimiento.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        datosPersonales.add(txtFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 216, 122, -1));

        txtTelefono.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        datosPersonales.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 248, 122, -1));

        txtEmail.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        datosPersonales.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 280, 160, -1));

        txtCalle.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        datosPersonales.add(txtCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 310, 160, -1));

        txtNumero.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        txtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroActionPerformed(evt);
            }
        });
        datosPersonales.add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 340, 122, -1));

        txtPiso.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        txtPiso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPisoActionPerformed(evt);
            }
        });
        datosPersonales.add(txtPiso, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 370, 122, -1));

        txtDpto.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        txtDpto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDptoActionPerformed(evt);
            }
        });
        datosPersonales.add(txtDpto, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 400, 122, -1));

        btnModificar.setBackground(new java.awt.Color(0, 0, 0));
        btnModificar.setFont(new java.awt.Font("Gill Sans MT", 3, 18)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(0, 153, 153));
        btnModificar.setText("modificar datos");
        btnModificar.setBorderPainted(false);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        datosPersonales.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 520, -1, -1));

        lbNombre.setFont(new java.awt.Font("Gill Sans MT", 3, 18)); // NOI18N
        lbNombre.setForeground(new java.awt.Color(0, 153, 153));
        lbNombre.setText("Nombre");
        datosPersonales.add(lbNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 115, 99, 18));

        btnSalir.setBackground(new java.awt.Color(0, 0, 0));
        btnSalir.setFont(new java.awt.Font("Gill Sans MT", 3, 18)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(0, 153, 153));
        btnSalir.setText("Salir");
        btnSalir.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        datosPersonales.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 70, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dnarelo.gif"))); // NOI18N
        datosPersonales.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTabbeDatos.addTab("Datos Personales", datosPersonales);

        getContentPane().add(jTabbeDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 800, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        VentanaPersona t=new VentanaPersona();
        t.setVisible(true);
        t.setLocationRelativeTo(null); // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        TestMainAUsar t=new TestMainAUsar();
        t.setVisible(true);
        t.setLocationRelativeTo(null); // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
       int dniAux=Integer.parseInt(txtDni.getText());
        Persona aux=getPersonaByDni(dniAux);
        aux.setTelefono(txtTelefono.getText());
        aux.setEmail(txtEmail.getText());
        aux.setCalle(txtCalle.getText());
        int numAux=Integer.parseInt(txtNumero.getText());
        aux.setNumero(numAux);
        int pisoAux=Integer.parseInt(txtPiso.getText());
        aux.setNumero(pisoAux);
        int dptoAux=Integer.parseInt(txtDpto.getText());
        aux.setNumero(dptoAux);
        ControllerPersona.actualizar(aux);
        
    }//GEN-LAST:event_btnModificarActionPerformed

    private void txtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroActionPerformed

    private void txtNrohcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNrohcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNrohcActionPerformed

    private void txtDptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDptoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDptoActionPerformed

    private void txtDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDniActionPerformed

    private void txtPisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPisoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPisoActionPerformed

    private void tablaSedesComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_tablaSedesComponentAdded
       
 
        
    

       // TODO add your handling code here:
    }//GEN-LAST:event_tablaSedesComponentAdded

    private void tablaSedesComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_tablaSedesComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaSedesComponentRemoved

    private void btnMostrarSedesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarSedesActionPerformed
        // TODO add your handling code here:
        List<Sede> listado = new ArrayList();
        listado = ControllerSede.listarSedes();

        Object O[] = null;
        for (int i = 0; i < listado.size(); i++) {
            modelo.addRow(O);
            Sede getP = (Sede) listado.get(i);
            modelo.setValueAt(getP.getIdSede(), i, 0);
            modelo.setValueAt(getP.getNombre(), i, 1);
            modelo.setValueAt(getP.getCalle(), i, 2);
            modelo.setValueAt(getP.getNumero(), i, 3);
            modelo.setValueAt(getP.getPiso(), i, 4);
            modelo.setValueAt(getP.getLetra(), i, 5);
            modelo.setValueAt(getP.getTelefono(), i, 6);
            modelo.setValueAt(getP.getEmail(), i, 7);
        }
    }//GEN-LAST:event_btnMostrarSedesActionPerformed

    private void btnMostrarAlergiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarAlergiasActionPerformed
        List<String> listado;
        int dniAux=Integer.parseInt(txtDni.getText());
        Persona aux=getPersonaByDni(dniAux);
        HistoriaClinica auxHC;
        auxHC=ControllerHistoriaClinica.HistorialPorId(aux.getNroHistoriaClinica());
        listado = auxHC.getAlergias();

        Object O[] = null;
        for (int i = 0; i < listado.size(); i++) {
            modeloA.addRow(O);
            String getA =listado.get(i);
            modeloA.setValueAt(getA, i, 0);
            modeloA.setValueAt(getA, i, 1);
            
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMostrarAlergiasActionPerformed

    private void btnMostrarVacunasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarVacunasActionPerformed
        List<Vacuna> listado;// = new ArrayList();
        int dniAux = Integer.parseInt(txtDni.getText());
        Persona aux = getPersonaByDni(dniAux);
        listado = aux.getVacunas();
        Object O[] = null;
        for (int i = 0; i < listado.size(); i++) {
            modeloV.addRow(O);
            Vacuna getP = (Vacuna) listado.get(i);
            modeloV.setValueAt(getP.getIdVacuna(), i, 0);
            modeloV.setValueAt(getP.getNombre(), i, 1);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMostrarVacunasActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       System.exit(0); // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(0);// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        System.exit(0);// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       System.exit(0); // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPersona().setVisible(true);
            }
        });
    }

    public void setTxtApellido(String txtApellido) {
        this.txtApellido.setText(txtApellido); 
    }

    public void setTxtCalle(String txtCalle) {
        this.txtCalle.setText(txtCalle);
    }

    public void setTxtDni(String txtDni) {
        this.txtDni.setText(txtDni);
    }

    public void setTxtDpto(String txtDpto) {
        this.txtDpto.setText(txtDpto);
    }

    public void setTxtEmail(String txtEmail) {
        this.txtEmail.setText(txtEmail);
    }

    public void setTxtFechaNacimiento(String txtFechaNacimiento) {
        this.txtFechaNacimiento.setText(txtFechaNacimiento);
    }

    public void setTxtNombre(String txtNombre) {
        this.txtNombre.setText(txtNombre);
    }

    public void setTxtNrohc(String txtNrohc) {
        this.txtNrohc.setText(txtNrohc);
    }

    public void setTxtNumero(String txtNumero) {
        this.txtNumero.setText(txtNumero);
    }

    public void setTxtPiso(String txtPiso) {
        this.txtPiso.setText(txtPiso);
    }

    public void setTxtTelefono(String txtTelefono) {
        this.txtTelefono.setText(txtTelefono);
    }

    public JPanel getSedes() {
        return sedes;
    }

    public void setSedes(JPanel sedes) {
        this.sedes = sedes;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame MuestraDatos;
    private javax.swing.JPanel alergias;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnMostrarAlergias;
    private javax.swing.JButton btnMostrarHC;
    private javax.swing.JButton btnMostrarSedes;
    private javax.swing.JButton btnMostrarVacunas;
    private javax.swing.JButton btnSalir;
    private javax.swing.JPanel datosPersonales;
    private javax.swing.JLabel fondo;
    private javax.swing.JPanel historiaClinica;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jCalle;
    private javax.swing.JLabel jCalle1;
    private javax.swing.JLabel jEmail;
    private javax.swing.JLabel jEmail1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPaneSedes;
    private javax.swing.JTabbedPane jTabbeDatos;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableAlergias;
    private javax.swing.JTable jTableVacuna;
    private javax.swing.JLabel jlApellido;
    private javax.swing.JLabel jlApellido1;
    private javax.swing.JLabel jlDireccion;
    private javax.swing.JLabel jlDni;
    private javax.swing.JLabel jlDni1;
    private javax.swing.JLabel jlFechaNac;
    private javax.swing.JLabel jlFechaNac1;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JLabel jlNroHC;
    private javax.swing.JLabel jlNroHC1;
    private javax.swing.JLabel jlPiso;
    private javax.swing.JLabel jlPiso1;
    private javax.swing.JLabel jlTelefono;
    private javax.swing.JLabel jlTelefono1;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JPanel sedes;
    private javax.swing.JTable tablaSedes;
    private java.awt.TextField txtApellido;
    private java.awt.TextField txtCalle;
    private java.awt.TextField txtDni;
    private java.awt.TextField txtDpto;
    private java.awt.TextField txtEmail;
    private java.awt.TextField txtFechaNacimiento;
    public java.awt.TextField txtNombre;
    private java.awt.TextField txtNrohc;
    private java.awt.TextField txtNumero;
    private java.awt.TextField txtPiso;
    private java.awt.TextField txtTelefono;
    private javax.swing.JPanel vacunas;
    private javax.swing.JLabel verApellido;
    private javax.swing.JLabel verCalle;
    private javax.swing.JLabel verDni;
    private javax.swing.JLabel verDpto;
    private javax.swing.JLabel verEmail;
    private javax.swing.JLabel verFechaNac;
    private javax.swing.JLabel verNombre;
    private javax.swing.JLabel verNroHC;
    private javax.swing.JLabel verNumero;
    private javax.swing.JLabel verPiso;
    private javax.swing.JLabel verTelefono;
    // End of variables declaration//GEN-END:variables

    public JTable getTablaSedes() {
        return tablaSedes;
    }
   
 private void CrearModeloSede(){
 try {
 modelo = (new DefaultTableModel(
 null, new String [] {
 "id","Nombre",
 "calle","numero","piso","depto","telefono","email"}){
 Class[] types = new Class [] {
 java.lang.String.class,
 java.lang.String.class,
 java.lang.String.class,
 java.lang.String.class,
 java.lang.String.class,
 java.lang.String.class,
 java.lang.String.class,
 java.lang.String.class
 };
 boolean[] canEdit = new boolean [] {
 false,false,false,false
 };
 @Override
 public Class getColumnClass(int columnIndex) {
 return types [columnIndex];
 }
 @Override
 public boolean isCellEditable(int rowIndex, int colIndex){
 return canEdit [colIndex];
 }
 });
 tablaSedes.setModel(modelo);
 } catch (Exception e) {
 JOptionPane.showMessageDialog(null,e.toString()+"error2");
 }
 }
private void CrearModeloAlergia(){
 try {
 modeloA = (new DefaultTableModel(
 null, new String [] {
 "id","Nombre"}){
 Class[] types = new Class [] {
 java.lang.String.class,
 java.lang.String.class
 };
 boolean[] canEdit = new boolean [] {
 false,false,false,false
 };
 @Override
 public Class getColumnClass(int columnIndex) {
 return types [columnIndex];
 }
 @Override
 public boolean isCellEditable(int rowIndex, int colIndex){
 return canEdit [colIndex];
 }
 });
 jTableAlergias.setModel(modeloA);
 } catch (Exception e) {
 JOptionPane.showMessageDialog(null,e.toString()+"error2");
 }
 }
private void CrearModeloVacuna(){
 try {
 modeloV = (new DefaultTableModel(
 null, new String [] {
 "id","Nombre"}){
 Class[] types = new Class [] {
 java.lang.String.class,
 java.lang.String.class
 };
 boolean[] canEdit = new boolean [] {
 false,false,false,false
 };
 @Override
 public Class getColumnClass(int columnIndex) {
 return types [columnIndex];
 }
 @Override
 public boolean isCellEditable(int rowIndex, int colIndex){
 return canEdit [colIndex];
 }
 });
 jTableVacuna.setModel(modeloV);
 } catch (Exception e) {
 JOptionPane.showMessageDialog(null,e.toString()+"error2");
 }
 }
}
