/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sidc.vista;

import com.sidc.clases.Persona;
import com.sidc.controllers.ControllerPersona;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author julian
 */
public class VerDatos extends javax.swing.JFrame {
        //private int numEntero = Integer.parseInt(IngresoPersona.txtUsuario.getText());
        //private Persona p =ControllerPersona.getPersonaByDni(numEntero);
    /**
     * Creates new form VerDatos
     */
    public VerDatos() {
        initComponents();
        Persona p=null;
        
    }
     public Image getIconImage(){
        Image retValue=Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/SIDC (1).png"));
        return retValue;
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textField1 = new java.awt.TextField();
        btnAtras = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jCalle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlTelefono = new javax.swing.JLabel();
        jlNombre = new javax.swing.JLabel();
        jlApellido = new javax.swing.JLabel();
        jlDni = new javax.swing.JLabel();
        jlFechaNac = new javax.swing.JLabel();
        jEmail = new javax.swing.JLabel();
        jlDireccion = new javax.swing.JLabel();
        verNombre = new javax.swing.JLabel();
        verApellido = new javax.swing.JLabel();
        verDni = new javax.swing.JLabel();
        verFechaNac = new javax.swing.JLabel();
        verTelefono = new javax.swing.JLabel();
        verEmail = new javax.swing.JLabel();
        verCalle = new javax.swing.JLabel();
        verNumero = new javax.swing.JLabel();
        verPiso = new javax.swing.JLabel();
        jlPiso = new javax.swing.JLabel();
        verDpto = new javax.swing.JLabel();
        jlNroHC = new javax.swing.JLabel();
        verNroHC = new javax.swing.JLabel();

        textField1.setText("textField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAtras.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jCalle.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        jCalle.setText("Calle");
        jCalle.setFocusTraversalPolicyProvider(true);

        jLabel1.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        jLabel1.setText("Numero");

        jLabel3.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        jLabel3.setText("Departamento");

        jlTelefono.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        jlTelefono.setText("Telefono");

        jlNombre.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        jlNombre.setText("Nombre");

        jlApellido.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        jlApellido.setText("Apellido");

        jlDni.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        jlDni.setText("D.N.I.");

        jlFechaNac.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        jlFechaNac.setText("Fecha de nacmiento");

        jEmail.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        jEmail.setText("Email");

        jlDireccion.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        jlDireccion.setText("Direccion");

        jlPiso.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        jlPiso.setText("Piso");

        jlNroHC.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        jlNroHC.setText("Numero Historia Cinica");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 132, Short.MAX_VALUE)
                        .addComponent(jlDireccion)
                        .addGap(110, 110, 110)
                        .addComponent(btnAtras)
                        .addGap(33, 33, 33)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlApellido)
                                    .addComponent(jlDni)
                                    .addComponent(jlFechaNac)
                                    .addComponent(jlTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(96, 96, 96)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(verCalle)
                                    .addComponent(verEmail)
                                    .addComponent(verTelefono)
                                    .addComponent(verFechaNac)
                                    .addComponent(verDni)
                                    .addComponent(verApellido)
                                    .addComponent(verNombre)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jlPiso)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(172, 172, 172)
                                        .addComponent(verNumero)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(verPiso)
                                    .addComponent(verDpto)
                                    .addComponent(verNroHC)))
                            .addComponent(jlNroHC))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNroHC)
                    .addComponent(verNroHC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNombre)
                    .addComponent(verNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlApellido)
                    .addComponent(verApellido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDni)
                    .addComponent(verDni))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlFechaNac)
                    .addComponent(verFechaNac))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTelefono)
                    .addComponent(verTelefono))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEmail)
                    .addComponent(verEmail))
                .addGap(8, 8, 8)
                .addComponent(jlDireccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(verCalle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(verNumero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(verPiso)
                    .addComponent(jlPiso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(verDpto)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAtras)
                    .addComponent(jButton2))
                .addGap(188, 188, 188))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
       VentanaPersona t=new VentanaPersona();
       t.setVisible(true);
       t.setLocationRelativeTo(null); // TODO add your handling code here:
       this.dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        TestMainAUsar t=new TestMainAUsar();
       t.setVisible(true);
       t.setLocationRelativeTo(null); // TODO add your handling code here:
       this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerDatos().setVisible(true);
            }
        });
    }

    public void setVerApellido(String verApellido) {
        this.verApellido.setText(verApellido);
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jCalle;
    private javax.swing.JLabel jEmail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jlApellido;
    private javax.swing.JLabel jlDireccion;
    private javax.swing.JLabel jlDni;
    private javax.swing.JLabel jlFechaNac;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JLabel jlNroHC;
    private javax.swing.JLabel jlPiso;
    private javax.swing.JLabel jlTelefono;
    private java.awt.TextField textField1;
    private javax.swing.JLabel verApellido;
    private javax.swing.JLabel verCalle;
    private javax.swing.JLabel verDni;
    private javax.swing.JLabel verDpto;
    private javax.swing.JLabel verEmail;
    private javax.swing.JLabel verFechaNac;
    private javax.swing.JLabel verNombre;
    private javax.swing.JLabel verNroHC;
    private javax.swing.JLabel verNumero;
    private javax.swing.JLabel verPiso;
    private javax.swing.JLabel verTelefono;
    // End of variables declaration//GEN-END:variables
}
